// Keep the native runtime in focused units while preserving one translation
// unit for Zygisk's registration macros and the existing internal linkage.
#include "runtime_native_prelude.inc"
#include "runtime_native_common.inc"
#include "runtime_bridge_protocol.inc"
#include "runtime_bridge_broker.inc"
#include "runtime_probe_elf.inc"
#include "runtime_probe_inspection.inc"
#include "runtime_probe_owners.inc"
#include "runtime_probe_discovery.inc"
#include "runtime_encounter_owners.inc"
#include "runtime_probe_candidates.inc"
#include "runtime_main_thread_bridge.inc"
#include "runtime_scene_owners.inc"
#include "runtime_main_thread_loader.inc"
#include "runtime_main_thread_unity.inc"
#include "runtime_main_thread_actions.inc"
#include "runtime_probe_gesture.inc"
#include "runtime_probe_diagnostic.inc"
#include "runtime_probe_inventory.inc"
#include "runtime_probe_survey.inc"
#include "runtime_companion.inc"
#include "runtime_map_reader.inc"
#include "runtime_map_dictionary.inc"
#include "runtime_probe_map_instance.inc"
#include "runtime_observation.inc"
#include "runtime_map_actions.inc"
#include "runtime_encounter_actions.inc"
#include "runtime_action_common.inc"
#include "runtime_action_catch.inc"
#include "runtime_action_open_encounter.inc"
#include "runtime_actions.inc"
}  // namespace

#include "runtime_module.inc"
